[package]
name = "pwww"
version = "0.3.0"
edition = "2024"

[profile.release]
strip = true
lto = true

[dependencies]
anyhow = "1.0.100"
clap = "4.5.53"
common = { path = "../common" }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
