[build]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    """\
    apt-get update && apt-get --assume-yes install \
        libwayland-dev:$CROSS_DEB_ARCH \
        wayland-protocols \
        libxkbcommon-dev:$CROSS_DEB_ARCH \
        pkg-config
    """,
]
