name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build_and_upload:
    needs: create_release
    name: Create and upload artifacts for pwwwd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_triplet:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v5
      - uses: mozilla-actions/sccache-action@v0.0.9
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: taiki-e/install-action@cross

      - name: Build
        run: |
          cross build --release --target ${{ matrix.target_triplet }}
          cross build --release --target ${{ matrix.target_triplet }} -p pwww

      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp target/${{ matrix.target_triplet }}/release/pwwwd dist/pwwwd-${{ github.ref_name }}-${{ matrix.target_triplet }}
          cp target/${{ matrix.target_triplet }}/release/pwww dist/pwww-${{ github.ref_name }}-${{ matrix.target_triplet }}

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/pwwwd-${{ github.ref_name }}-${{ matrix.target_triplet }}
            dist/pwww-${{ github.ref_name }}-${{ matrix.target_triplet }}
          token: ${{ secrets.GITHUB_TOKEN }}
